act_entropy: 0.0003
kl_free: 1.0
imag_horizon: 15
horizon: 333
lamb: 0.95
compile: true
device: ${device}
lr: 4.0e-05
agc: 0.3
pmin: 0.001
eps: 1.0e-20
beta1: 0.9
beta2: 0.999
warmup: 1000
slow_target_update: 1
slow_target_fraction: 0.02
loss_scales:
  recon: 1.0
  rew: 1.0
  con: 1.0
  dyn: 1.0
  rep: 0.1
  policy: 1.0
  value: 1.0
  repval: 0.3
rssm:
  stoch: 32
  deter: ${model.deter}
  hidden: ${model.hidden}
  discrete: ${model.discrete}
  img_layers: 2
  obs_layers: 1
  dyn_layers: 1
  blocks: 8
  act: ${model.act}
  unimix_ratio: 0.01
  device: ${device}
encoder:
  mlp_keys: state
  mlp:
    shape: null
    layers: 3
    units: ${model.units}
    act: ${model.act}
    norm: ${model.norm}
    device: ${device}
    outscale: null
    symlog_inputs: true
    name: mlp_encoder
decoder:
  mlp_keys: state
  mlp_dist:
    name: symlog_mse
  mlp:
    shape: null
    layers: 3
    units: ${model.units}
    act: ${model.act}
    norm: ${model.norm}
    dist:
      name: identity
    device: ${device}
    outscale: 1.0
    symlog_inputs: false
    name: mlp_decoder
reward:
  shape:
  - 255
  layers: 1
  units: ${model.units}
  act: ${model.act}
  norm: ${model.norm}
  dist:
    name: symexp_twohot
    bin_num: 255
  outscale: 0.0
  device: ${device}
  symlog_inputs: false
  name: reward
cont:
  shape:
  - 1
  layers: 1
  units: ${model.units}
  act: ${model.act}
  norm: ${model.norm}
  dist:
    name: binary
  outscale: 1.0
  device: ${device}
  symlog_inputs: false
  name: cont
actor:
  shape: null
  layers: 3
  units: ${model.units}
  act: ${model.act}
  norm: ${model.norm}
  device: ${device}
  dist:
    name: bounded_normal
    min_std: 0.1
    max_std: 1.0
  outscale: 0.01
  symlog_inputs: false
  name: actor
critic:
  shape:
  - 255
  layers: 3
  units: ${model.units}
  act: ${model.act}
  norm: ${model.norm}
  device: ${device}
  dist:
    name: symexp_twohot
    bin_num: 255
  outscale: 0.0
  symlog_inputs: false
  name: value
deter: 2048
hidden: 256
discrete: 16
units: 256
act: SiLU
norm: true
context:
  mode: hidden
  key: context
  window: 1
  normalize: true
  low: ${env.context_low}
  high: ${env.context_high}
